regenerated

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -15,7 +15,7 @@
 # NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
 # WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 
-# From configure.in Revision: 1.272 
+# From configure.in Revision: 1.273 
 
 # libtool.m4 - Configure libtool for the host system. -*-Shell-script-*-
 ## Copyright 1996, 1997, 1998, 1999, 2000, 2001
@@ -2246,7 +2246,7 @@ fi
 
 			if test "$use_openssl" = "include/openssl/opensslv.h"
 			then
-				{ echo "configure: error: openssl was not fine in any of $openssldirs; use --with-openssl=/path" 1>&2; exit 1; }
+				{ echo "configure: error: OpenSSL was not found in any of $openssldirs; use --with-openssl=/path" 1>&2; exit 1; }
 			fi
 		fi
 		USE_OPENSSL='-DOPENSSL'
