Reformat shell scripts with shfmt
All changes in this commit were automated using the command:

  shfmt -w -i 2 -ci -bn bin/tests/system/ util/ $(find bin/tests/system/ -name "*.sh.in")

By default, only *.sh and files without extension are checked, so
*.sh.in files have to be added additionally. (See mvdan/sh#944)

(manually replayed commit 4cb8b13987b930952238cc88e84272b8cf911933)

diff --git a/bin/tests/system/conf.sh.in b/bin/tests/system/conf.sh.in
--- a/bin/tests/system/conf.sh.in
+++ b/bin/tests/system/conf.sh.in
@@ -33,12 +33,12 @@ export CHECKDS=$TOP/bin/python/dnssec-checkds
 export CHECKZONE=$TOP/bin/check/named-checkzone
 export COVERAGE=$TOP/bin/python/dnssec-coverage
 export DDNSCONFGEN=$TOP/bin/confgen/ddns-confgen
-if [ -z "$TSAN_OPTIONS" ]; then  # workaround for GL#4119
-    export DELV=$TOP/bin/delv/delv
-    export RESOLVE=$TOP/bin/tests/system/resolve
+if [ -z "$TSAN_OPTIONS" ]; then # workaround for GL#4119
+  export DELV=$TOP/bin/delv/delv
+  export RESOLVE=$TOP/bin/tests/system/resolve
 else
-    export DELV=:
-    export RESOLVE=:
+  export DELV=:
+  export RESOLVE=:
 fi
 export DIG=$TOP/bin/dig/dig
 export DNSTAPREAD=$TOP/bin/tools/dnstap-read
@@ -105,8 +105,8 @@ export PSSUSPEND=
 #
 export PERL=@PERL@
 if ! test -x "$PERL"; then
-    echo "Perl interpreter is required for system tests."
-    exit 77
+  echo "Perl interpreter is required for system tests."
+  exit 77
 fi
 export PYTHON=@PYTHON@
 
@@ -114,7 +114,6 @@ export PYTHON=@PYTHON@
 # Determine if we support various optional features.
 #
 export CRYPTO=@CRYPTO@
-
 
 # Load common values shared between windows and unix/linux.
 . $TOP/bin/tests/system/conf.sh.common
