Make Perl interpreter required for system tests
This change has no practical impact, as Perl was already required for
all system tests, this check only makes it more explicit.

(cherry picked from commit 084d72d1d5ea38f4ccc600fd04d61fed1c3124c3)

conf.sh.win32 was modified in addition of the mentioned commit.

diff --git a/bin/tests/system/conf.sh.in b/bin/tests/system/conf.sh.in
--- a/bin/tests/system/conf.sh.in
+++ b/bin/tests/system/conf.sh.in
@@ -99,6 +99,10 @@ export PSSUSPEND=
 # Interpreters for system tests detected by configure
 #
 export PERL=@PERL@
+if ! test -x "$PERL"; then
+    echo "Perl interpreter is required for system tests."
+    exit 77
+fi
 export PYTHON=@PYTHON@
 
 #
