Make Python interpreter required for system tests
This introduces a Python dependency for running system tests. It is
needed in order to:
  - write new test control scripts in Python
  - gradually rewrite old Perl scripts into Python if needed
  - eventually introduce pytest as the new test runner framework

This commit is not intended to be backported to 9.16.

diff --git a/bin/tests/system/conf.sh.in b/bin/tests/system/conf.sh.in
--- a/bin/tests/system/conf.sh.in
+++ b/bin/tests/system/conf.sh.in
@@ -86,6 +86,10 @@ if ! test -x "$PERL"; then
     exit 77
 fi
 export PYTHON=$(command -v "@PYTHON@" || true)
+if ! test -x "$PYTHON"; then
+    echo "Python interpreter is required for system tests."
+    exit 77
+fi
 
 # Load common values
 . $TOP_SRCDIR/bin/tests/system/conf.sh.common
