Make Perl interpreter required for system tests
This change has no practical impact, as Perl was already required for
all system tests, this check only makes it more explicit.

diff --git a/bin/tests/system/conf.sh.in b/bin/tests/system/conf.sh.in
--- a/bin/tests/system/conf.sh.in
+++ b/bin/tests/system/conf.sh.in
@@ -80,7 +80,11 @@ export PYTEST=@PYTEST@
 #
 # Interpreters for system tests detected by configure
 #
-export PERL=$(command -v "@PERL@")
+export PERL=$(command -v "@PERL@" || true)
+if ! test -x "$PERL"; then
+    echo "Perl interpreter is required for system tests."
+    exit 77
+fi
 export PYTHON=$(command -v "@PYTHON@" || true)
 
 # Load common values
